---
- hosts: master

  become: yes
  become_method: sudo

  vars:
    jenkins_repo_url: https://pkg.jenkins.io/redhat/jenkins.repo
    jenkins_repo_key_url: https://pkg.jenkins.io/redhat/jenkins.io.key
    jenkins_admin_password: "{{ lookup('password', 'generated_bits/jenkins_admin_password length=20') }}"

  tasks:
  - name: Mount the Jenkins data directory
    mount:
      path: /var/lib/jenkins
      src: /dev/sdb
      fstype: ext4
      state: present

  - name: Ensure Jenkins repo is enabled
    get_url:
      url: "{{ jenkins_repo_url }}"
      dest: /etc/yum.repos.d/jenkins.repo

  - name: Add Jenkins repo GPG key
    rpm_key:
      state: present
      key: "{{ jenkins_repo_key_url }}"

  - name: Ensure nginx (reverse proxy) repo is enabled
    copy:
      src: ./master_cfg/nginx.repo
      dest: /etc/yum.repos.d/nginx.repo

  - name: Ensure dependencies are installed
    package:
      name:
      - curl
      - libselinux-python
      - initscripts
      - java
      state: installed

  - name: Install Jenkins
    package:
      name: jenkins
      state: present

  - name: Set up Jenkins user
    user:
      name: jenkins
      comment: "Jenkins master user"
      home: /var/lib/jenkins/home
      move_home: yes
      generate_ssh_key: yes  # we will use this key to connect to workers

  - name: Fetch jenkins public key from master to local machine
    fetch:
      src: /var/lib/jenkins/home/.ssh/id_rsa.pub
      dest: ./master_cfg/master_id_rsa.pub
      flat: yes
      fail_on_missing: yes

  - name: Set up Jenkins start-up Java options
    lineinfile:
      dest: /etc/sysconfig/jenkins
      regexp: '^JENKINS_JAVA_OPTIONS='
      line: 'JENKINS_JAVA_OPTIONS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"'  # the setup wizard is a security risk

  - name: Set up Jenkins service
    service:
      name: jenkins
      enabled: yes
      state: started

  - name: Install nginx (reverse proxy)
    package:
      name: nginx
      state: installed

  - name: Set-up a directory for TLS certificates for nginx
    file:
      path: /etc/nginx/tls
      state: directory
      mode: 0755
      owner: root
      group: root

  - name: Check whether a TLS key for nginx is present
    stat:
      path: /etc/nginx/tls/server.key
    register: nginx_tls_key

# no clue if I am doing this right...
  - name: Generate self signed temporary TLS certificate for nginx
    command: openssl req -new -nodes -x509 -subj "/C=US/ST=Massachusetts/L=Boston/O=IT/CN=jenkins.open-scap.org" -days 365 -keyout /etc/nginx/tls/server.key -out /etc/nginx/tls/server.crt -extensions v3_ca creates=/etc/nginx/tls/server.crt
    when: nginx_tls_key.stat.exists == False  # only if letsencrypt's cert is missing

  - name: Config nginx (reverse proxy) with jenkins.conf
    copy:
      src: ./master_cfg/nginx_jenkins.conf
      dest: /etc/nginx/conf.d/jenkins.conf
    notify: restart nginx

  - name: Tell SELinux to let nginx (reverse proxy) connect to network
    seboolean:
      name: httpd_can_network_connect
      state: yes
      persistent: yes

  - name: Set up nginx (reverse proxy) service
    service:
      name: nginx
      enabled: yes
      state: started

  - name: Set up Jenkins admin web UI password
    debug:
      msg: "Jenkins admin pw: {{ jenkins_admin_password }}"
    # TODO: actually implement this

  handlers:
  - name: restart nginx
    service: name=nginx state=restarted
