---
- hosts: all

  become: yes
  become_method: sudo

  tasks:
  - name: upgrade all packages
    yum:
      name: '*'
      state: latest

  - name: Set hostname
    hostname:
      name: "{{ inventory_hostname }}"

  - name: Set up /etc/hosts with IPv4 of master and workers
    lineinfile:
      dest: /etc/hosts
      regexp: ".*{{ item }}$"
      line: "{{ hostvars[item].ansible_default_ipv4.address }} {{item}}"
      state: present
    when: hostvars[item].ansible_default_ipv4.address is defined
    with_items: "{{ groups['all'] }}"

  # EPEL is needed for python-pip package, which is required for python-jenkins
  # and lxml -these are required by jenkins_job module. jenkins_job is required
  # by us (on master). Also required for linkchecker (on workers)
  - name: Add EPEL 7
    yum_repository:
      name: epel
      description: Extra Packages for Enterprise Linux 7 - $basearch
      mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
      failovermethod: priority
      gpgkey: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7Server
      gpgcheck: yes
    when: ansible_distribution == 'RedHat' and ansible_distribution_version.split(".")[0] == "7"

  - name: Add EPEL 6
    yum_repository:
      name: epel
      description: Extra Packages for Enterprise Linux 6 - $basearch
      mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-6&arch=$basearch
      failovermethod: priority
      gpgkey: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-6Server
      gpgcheck: yes
    when: ansible_distribution == 'RedHat' and ansible_distribution_version.split(".")[0] == "6"

  - name: Install pip
    package:
      name:
      - python-pip
      state: installed
    when: ansible_distribution == 'RedHat' and ansible_distribution_version.split(".")[0] <= "7"

  - name: Install pip3
    package:
      name:
      - python3-pip
      state: installed
    when: ansible_distribution != 'RedHat' or ansible_distribution_version.split(".")[0] >= "8"

  - name: Install cronie
    package:
      name: cronie
      state: present

  - name: Enable cronie service
    service:
      name: crond
      enabled: yes
      state: started

# despite being called yum-cron this works on RHEL and Fedora
  - name: Install yum-cron
    package:
      name: yum-cron
      state: present

  - name: Copy yum-cron.conf over
    copy:
      src: shared_cfg/yum-cron.conf
      dest: /etc/yum/yum-cron.conf

  - name: Enable yum-cron service
    service:
      name: yum-cron
      enabled: yes
      state: started

  - name: Install tuned (performance tuning)
    package:
      name: tuned
      state: present

  - name: Start tuned (performance tuning)
    service:
      name: tuned
      enabled: yes
      state: started

  - name: Enable the virtual-guest performance profile
    shell: tuned-adm profile virtual-guest

  - name: Disable kdump
    service:
      name: kdump
      enabled: no
      state: stopped
    ignore_errors: yes  # fails if kdump is not even available

  - name: Disable sssd  # we don't need its features
    service:
      name: sssd
      enabled: no
      state: stopped
    ignore_errors: yes  # fails if sssd is not even available

  - name: Disable password auth in sshd
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "^#?PasswordAuthentication"
      line: "PasswordAuthentication no"
    notify: restart sshd

  handlers:
  - name: restart sshd
    service: name=sshd state=restarted
