---
- hosts:
  - worker_rhel6
  - worker_rhel7
  - worker_fedora

  become: yes
  become_method: sudo

  tasks:
  - name: Set up Jenkins user
    user:
      name: jenkins
      comment: "Jenkins user"

  # we use the public key to connect to slaves from jenkins master
  - name: Authorize master's jenkins user public key
    authorized_key:
      user: jenkins
      key: "{{ lookup('file', './master_cfg/master_id_rsa.pub') }}"
      exclusive: yes  # only need one key for "jenkins" user, users can still connect as ec2-user
      state: present

  # RHEL7 optional RPMs are required for -devel packages
  # we can't use yum_repository ansible module because it doesn't allow
  # modification of existing repo files, it's mainly for creating new files
  - name: Enable the rhel7 server optional RPMs repo
    ini_file:
      path: /etc/yum.repos.d/redhat-rhui.repo
      section: rhui-REGION-rhel-server-optional
      option: enabled
      value: yes
      create: no
      state: present
    when: ansible_distribution == 'RedHat'

  - name: Ensure general Jenkins dependencies are installed
    package:
      name:
        - java

  - name: Ensure OpenSCAP dependencies are installed
    package:
      name:
      - dbus-devel
      - libacl-devel
      - libblkid-devel
      - libcap-devel
      - libcurl-devel
      - libgcrypt-devel
      - libselinux-devel
      - libxml2-devel
      - libxslt-devel
      - make
      - openldap-devel
      - pcre-devel
      - perl-XML-Parser
      - perl-XML-XPath
      - perl-devel
      - python-devel
      - rpm-devel
      - swig
      - bzip2-devel
#      - GConf2-devel
      state: installed

  - name: Ensure SCAP Workbench dependencies are installed
    package:
      name:
      - cmake
      - gcc-c++
      - openssh-clients
      - util-linux
      - openscap-devel
      - qt-devel
      - polkit
#      - rubygem-asciidoctor
      state: installed

  - name: Ensure SCAP Security Guide dependencies are installed
    package:
      name:
      - cmake
      - openscap-utils
      - git
      state: installed
