---
- hosts:
  - worker_rhel6
  - worker_rhel7
  - worker_fedora

  become: yes
  become_method: sudo

  tasks:
  - name: Set hostname
    hostname:
      name: "{{ inventory_hostname }}"

  - name: Set up Jenkins user
    user:
      name: jenkins
      comment: "Jenkins user"

  - name: Ensure general Jenkins dependencies are installed
    package:
      name:
        - java

  - name: Ensure OpenSCAP dependencies are installed
    package:
      name:
      - dbus-devel
      - libacl-devel
      - libblkid-devel
      - libcap-devel
      - libcurl-devel
      - libgcrypt-devel
      - libselinux-devel
      - libxml2-devel
      - libxslt-devel
      - make
      - openldap-devel
      - pcre-devel
      - perl-XML-Parser
      - perl-XML-XPath
      - perl-devel
      - python-devel
      - rpm-devel
      - swig
      - bzip2-devel
#      - GConf2-devel
      state: installed

  - name: Ensure SCAP Workbench dependencies are installed
    package:
      name:
      - cmake
      - gcc-c++
      - openssh-clients
      - util-linux
      - openscap-devel
      - qt-devel
      - polkit
#      - rubygem-asciidoctor
      state: installed

  - name: Ensure SCAP Security Guide dependencies are installed
    package:
      name:
      - cmake
      - openscap-utils
      - git
      state: installed
