---
- hosts:
  - worker_rhel6
  - worker_rhel7
  - worker_fedora

  become: yes
  become_method: sudo

  tasks:
  - name: Set up Jenkins user
    user:
      name: jenkins
      comment: "Jenkins user"

  - name: Install prerequisites for authorized keys addition
    package:
      name:
      - libselinux-python

  # we use the public key to connect to slaves from jenkins master
  - name: Authorize master's jenkins user public key
    authorized_key:
      user: jenkins
      key: "{{ lookup('file', 'generated_bits/master_id_rsa.pub') }}"
      exclusive: yes  # only need one key for "jenkins" user, users can still connect as ec2-user
      state: present

  - name: Ensure general Jenkins dependencies are installed
    package:
      name:
        - java

  - name: Add the EPEL 7 repository
    yum_repository:
      name: epel
      description: Extra Packages for Enterprise Linux 7 - $basearch
      gpgcheck: yes
      gpgkey: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7Server
      mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
    when: ansible_distribution == 'RedHat' and ansible_distribution_version.split(".")[0] == "7"

  - name: Add the EPEL 6 repository
    yum_repository:
      name: epel
      description: Extra Packages for Enterprise Linux 6 - $basearch
      gpgcheck: yes
      gpgkey: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-6Server
      mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-6&arch=$basearch
    when: ansible_distribution == 'RedHat' and ansible_distribution_version.split(".")[0] == "6"

  - name: Ensure general build dependencies are installed
    package:
      name:
      - autoconf
      - automake
      - libtool
      - doxygen
      - git
      - rubygems
      - gawk
      - gcc
      - make
      - ccache

  - name: Ensure OpenSCAP has asciidoctor installed
    gem:
      name: asciidoctor
      user_install: no # let's install it everywhere

  - name: Ensure ninja-build is installed if applicable (RHEL7 or Fedora only)
    package:
      name:
      - ninja-build # for faster PR build
    when: ansible_distribution != 'RedHat' or ansible_distribution_version.split(".")[0] >= "7"

  - name: Copy ccache.conf over
    copy:
      src: shared_cfg/ccache.conf
      dest: /etc/ccache.conf

  - name: Ensure OpenSCAP dependencies are installed
    package:
      name:
      - dbus-devel
      - libacl-devel
      - libblkid-devel
      - libcap-devel
      - libcurl-devel
      - libgcrypt-devel
      - libselinux-devel
      - libxml2-devel
      - libxslt-devel
      - openldap-devel
      - pcre-devel
      - perl-XML-Parser
      - perl-XML-XPath
      - perl-devel
      - python-devel
      - rpm-devel
      - swig
      - bzip2-devel
      - GConf2-devel
      - sendmail  # the openscap OVAL mitre requires sendmail to complete
      - wget
      - lua
      - which
      - initscripts
      - chkconfig
      state: installed

  - name: Ensure procps is installed (OpenSCAP dependency)
    package:
      name:
      - procps
      state: installed
    when: ansible_distribution == 'RedHat' and ansible_distribution_version.split(".")[0] <= "6"

  - name: Ensure procps-ng is installed (OpenSCAP dependency)
    package:
      name:
      - procps-ng
      state: installed
    when: ansible_distribution != 'RedHat' or ansible_distribution_version.split(".")[0] >= "7"

  - name: Ensure OpenSCAP dependencies are running
    service:
      name: sendmail
      enabled: yes
      state: started

  - name: Ensure SCAP Workbench dependencies are installed
    package:
      name:
      - cmake
      - gcc-c++
      - openssh-clients
      - util-linux
      - openscap-devel
      - qt-devel
      - polkit
      - asciidoc
      state: installed

  - name: Ensure Qt5 is installed (Fedora and RHEL7 only, SCAP Workbench dependency)
    package:
      name:
      - qt5-qtbase-devel
      - qt5-qtxmlpatterns-devel
      state: installed
    when: ansible_distribution != 'RedHat' or ansible_distribution_version.split(".")[0] >= "7"

  - name: Ensure SCAP Security Guide dependencies are installed
    package:
      name:
      - cmake
      - openscap-utils
      - wget  # needed for the NIST test suite for SSG
      - PyYAML  # needed for the new SSG yaml port
      - ansible  # needed for ansible role syntax check
      state: installed

  - name: Ensure SCAP Security Guide dependencies are installed (Fedora only)
    package:
      name:
      - python2-jinja2  # needed for the new SSG yaml/jinja2 port
      - python2-pytest
      - python3-pytest  # needed for unit tests + coverage
      - python3-jinja2
      - python3-PyYAML
      state: installed
    when: ansible_distribution == 'Fedora'

  - name: Ensure that there is no Python2 on the system (Fedora only)
    package:
      name:
      - python2
      state: absent
    when: ansible_distribution == 'Fedora' and False  # We don't really want to remove it as long as linkchecker is python2-only.

  - name: Ensure SCAP Security Guide dependencies are installed (RHEL7 only)
    package:
      name:
      - python-jinja2  # needed for the new SSG yaml/jinja2 port
      - python2-pip  # needed for the linkchecker/pytest
      state: installed
    when: ansible_distribution == 'RedHat' and ansible_distribution_version.split(".")[0] >= "7"

  - name: Ensure SCAP Security Guide dependencies are installed (RHEL6 only)
    package:
      name:
      - python-jinja2  # needed for the new SSG yaml/jinja2 port
      - python-pip  # needed for the linkchecker/pytest
      state: installed
    when: ansible_distribution == 'RedHat' and ansible_distribution_version.split(".")[0] == "6"

  # this is the only common way across rhel/fedora.
  # It's url-based, because original project is dead, and fork is not established yet
  - name: Ensure linkchecker is installed for SCAP Security Guide checking
    pip:
      name:
      - git+https://github.com/linkcheck/linkchecker.git

  # RHEL may not have pytest
  - name: Ensure pytest coverage support is installed (RHEL only)
    pip:
      name:
      - pytest
    when: ansible_distribution == 'RedHat'

  - name: Ensure json2html is installed so it can convert profile statistics to HTML
    pip:
      name:
      - json2html
    when: ansible_distribution == 'Fedora'

  - name: Ensure OpenSCAP Daemon dependencies are installed (RHEL7 only)
    package:
      name:
      - dbus-python
      - gobject-introspection
      - pygobject2-devel
      state: installed
    when: ansible_distribution != 'RedHat' or ansible_distribution_version.split(".")[0] >= "7"

  - name: Ensure OpenSCAP Daemon extra dependencies are installed (Fedora only)
    package:
      name:
      - python-gobject-base
      - python-gobject
      - python3-dbus
      - pygobject3-devel
      - python3-gobject-base
      - python3-gobject
      state: installed
    when: ansible_distribution == 'Fedora'

  - name: Ensure OSCAP Anaconda dependencies are installed (RHEL7 only)
    package:
      name:
      - openscap-python
      - anaconda
      - python2-mock
      - python-nose
      - python-cpio
      - zanata-python-client
      state: installed
    when: ansible_distribution == 'RedHat' and ansible_distribution_version.split(".")[0] >= "7"

  - name: Ensure OpenSCAP Anaconda dependencies are installed (Fedora only)
    package:
      name:
      - openscap-python3
      - anaconda
      - python3-devel
      - python3-mock
      - python3-nose
      - python3-cpio
      - python3-pycurl
      - python3-kickstart
      - zanata-python-client
      state: installed
    when: ansible_distribution == 'Fedora'

